### ISSUE TITLE
Wrongspelling - P183

### ISSUE THREAD

**Issue by alexl4123** [sobteclib/sobtec2#2]
On Page 183 in the english PDF version, there is a spelling mistake (Subject "Neutrality").
Sentence:  No communications protocol  can be  given priority  in the  way  informaiton is distributed. And no data can have its content arbitrarily al-tered.
The error is at "information" -> informaiton

**Comment by sobteclib** [comment]
Thanks for your contribution. This is fixed in commit efab8f1 now. Eventually it will make it to the scribus PDF and printed versions too in subsequent print runs.
